version: '3'

services:
  tweetscollector:
    build:
      context: ./TweetsCollector
    ports:
      - 2200:8080
  sentimentanalysis:
    build:
      context: ./SentimentAnalysis
    ports:
      - 2201:8080
    depends_on:
      - tweetscollector
  reportservice:
    build:
      context: ./ReportService
    ports:
      - 2202:8080
    depends_on:
      - sentimentanalysis
  failoverservice:
    build:
      context: ./FailoverService
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - reportservice
  bpmn:
    build:
      context: ./BPMN
    ports:
     - 8080:8080